language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
deploy:
  provider: heroku
  api_key:
    secure: tFj5lNdsAKdTNmGdepP6RE+GxV6vbioUmAgk9y86TSDLzfDTvmJ9ql1l47ugk9Ylhmss6AZZng90fFdcu5acia4En3O7DiQoEFY/qhjyNpOqeMERPIwgr7Vd/xQIcu3763SEs3w6Clo5PIHaHX1JAUp2eb5QcmsCEf0mX0DabbQ=
  app:
    master: tylergoelz-www
    staging: tylergoelz-staging
  on:
    repo: yaboi/dotcom